export const testdata = {
  "email": "pavan@mailinator.com",
  "password": "abc@1234",
  "lastName": "Tester",
  "gender": "Male",
  "memberSearchPlaceholder": "search here...",
  "firstNamePrefix": "TestUser",
  "dashboardText": "Point of Sale",
  "membersManagementText": "Members Management",
  "addMemberText": "Add Member",
  "addButtonSelector": "button.btn.btn-primary[type=\"submit\"][data-mdb-dismiss=\"modal\"]:has-text(\"Add\")",
  "applyButtonSelector": "//button[text()='Apply']",
  "memberTableSelector": "table tr",
  "memberAddedText": "Member added successfully",
  "age": "25",
  "mobile": "9874563212",
  "memberEmail": "automation@gmail.com",
  "bloodGroup": "O+",
  "height": "165",
  "weight": "65",
  "city": "Hyderabad",
  "country": "India",
  "address": "Gachibowli",
  "referral": "Direct",
  "plansLinkText": "Plans, Slots & Addons",
  "createPlanLinkText": "Create Plan",
  "planName": "TestPlan",
  "validity": "20",
  "price": "1000",
  "saveButtonXPath": "//button[@type=\"submit\"][text()=\"Save\"]",
  "planSavedMessage": "Plan saved successfully",
  "searchInputXPath": "(//label[text()=\"search here...\"])[1]/../input",
  "pointOfSaleText": "Point of Sale",
  "planSearchPlaceholder": "Search Plan",
  "doneButtonText": "Done",
  "cashPaymentText": "Cash",
  "transactionSuccessText": "Transaction created successfully",
  "paymentSuccessText": "Payment Successful",
  "planNameSetup": "raghu",
  "Pausedays":"2",
  "trainer":"shiva shiva",
  "StaffPassword":"test@1234",
  "businessName": "automation",
  "firstName": "vamsi",
  "bussinessLastName": "tester",
  "state": "Andhra Pradesh",
  "businessEmail": "automation@mailinator.com",
  "phone": "9874563212",
  "bussinessCity": "Vijayawada",
  "shortcode": "test",
  "dateFormat": "DD/MM/YYYY",
  "membersCapacity": "50",
  "bussinessAddress": "Vijayawada",
  "number": "2",
  "phoneLabel": "+919874563212",
  "businessName1": "cloud",
  "firstName1": "shiva",
  "bussinessLastName1": "lucky",
  "state1": "Telangana",
  "businessEmail1": "cloud@mailinator.com",
  "phone1": "9874563213",
  "bussinessCity1": "Hyderabad",
  "shortcode1": "abc",
  "dateFormat1": "MM/DD/YYYY",
  "membersCapacity1": "60",
  "bussinessAddress1": "Hyderabad",
  "number1": "1.5",
  "phoneLabel1": "+919874563213",
  "giftCards": "GiftCards"
};